### ISSUE TITLE
[Bug][DedicatedServer] Stuck at Please wait for host to choose difficulty

### ISSUE THREAD

**Issue by zalexki** [Hazardu/ChampionsOfForest#1]
Am i missing something ?
 
this mod look promising. keep up the work (we trying pup in waiting for this)

**Comment by Hazardu** [comment]
Host has the mod too, right? While that phase it constantly requests difficulty info from the host

**Comment by zalexki** [comment]
There is no host only dedi (or should i somehow launch the mod on the dedi?).
Tried connecting with admin no success.

Ok thx!

**Comment by superseani2** [comment]
No simply make it so Everyone can choose there own difficulty's... Would fix problem. And create a nice Scale for PVP
