### ISSUE TITLE
Cannot kill rabbit with "left click"

### ISSUE THREAD

**Issue by SeeGEye** [Hazardu/ChampionsOfForest#10]
When holding a rabbit in your hand, then left clicking to kill it, the rabbit simply disappears. 

I'm not sure if this is COTF, Builder Core, or Builder Menu causing this. But since they all need to be enabled for COTF to work I figured I'd post it here.

Disabling COTF remedies this issue.

**Comment by Hazardu** [comment]
I've asked some people on modapi discord to test this.
How do bugs like this even come to be lol?
