### ISSUE TITLE
A statement on multiplayer saves

### ISSUE THREAD

**Issue by SeeGEye** [Hazardu/ChampionsOfForest#11]
To note:

When using LOTF on a multiplayer game, the client MUST save their game before the game closes to ensure their stats are kept. Since save data is stored natively at steamapps/common/theforest, the host can only save their own data and no one elses.

**Comment by Hazardu** [comment]
Yes, that's the limitation on how the forest multiplayer was made. Host has no access, can't read or modify most of clients stats. Everything is saved locally when saving at a tent, but it has a different path than COTF's save file.
This is not an issue with COTF, it's an issue with the game.
I've even used the same method to get lobby I'd as in actual game.

**Comment by SeeGEye** [comment]
I filed a previous "issue" saying that a client on my server _lost all of their data._ It was just a limitation of the game. I wasn't aware of this, so there was actually no issue with COTF at all.

**Comment by SeeGEye** [comment]
To add, I am a graphic designer and editor and would love to help you with your interface and graphics in the game - as well as grammatical corrections if you like!

**Comment by Hazardu** [comment]
Any help is greatly appreciated, if you have any interesting ideas, you can share them too 😊

**Comment by SeeGEye** [comment]
Where would be an easier place to communicate outside of GitHub?

**Comment by Hazardu** [comment]
Here, modapi discord https://discord.gg/DuMmSJ
