### ISSUE TITLE
Upgrades letting me carry more items do not work upon reloading game, only in the session that I bought them in

### ISSUE THREAD

**Issue by bschurman1** [Hazardu/ChampionsOfForest#12]
I have bought the upgrade that allows me to carry 3 sticks, 2 rocks, and 1 rope to which it worked in game. I eventually got off and got on again only to find that the maximum I can carry went back down. Putting another point into it "refreshes"  it and works like it should, but the same issue happens

**Comment by bschurman1** [comment]
Singleplayer btw

**Comment by Hazardu** [comment]
Sure, I will hop on the issue once I get more bugs to fix and I find interest in coming back to the game. Temporary fix would be to press reset stats button in the guide
