### ISSUE TITLE
'Size Matters' and 'Speed Matters' Perks Don't Work

### ISSUE THREAD

**Issue by Kerr007** [Hazardu/ChampionsOfForest#17]
https://github.com/Hazardu/ChampionsOfForest/blob/bb65d8b5215255bceb518e61feca4a3b2ee3b40d/Player/Perk.cs#L2497

These perks turn on their respective booleans: ProjectileDamageIncreasedBySize, ProjectileDamageIncreasedBySpeed, but these booleans never actually affect the ranged damage multiplier for the modded player.

**Comment by Kerr007** [comment]
On a similar note I've noticed that there are issues with the 'Glass Cannon' and 'Undestructable' perks on the Defense tree. 
Considering the formula is DamageReductionTotal => (DamageReduction) * (DamageReductionPerks), these perks do the opposite of their intention. Glass Cannon increases DamageReductionPerks by 1.1 and Undestructable increases it by .7.

**Comment by Hazardu** [comment]
Size matters and Speed matters are used in ArrowDamageMod.cs at line 498 and 507
Damage reduction starts at 1, which means you receive 100% dmg. Decreasing this value makes you take less damage. Increasing it makes you take more damage
