### ISSUE TITLE
Minor Bug :: Switching From Backpack Bow to Normal Bow

### ISSUE THREAD

**Issue by Kerr007** [Hazardu/ChampionsOfForest#18]
If you equip a bow from your backpack (5) and then hotkey for the standard game's bow, that bow will be invisible and unable to shoot.

**Comment by Hazardu** [comment]
A fix is incoming for this problem with update 1.6, which is currently being made on a separate branch.
Problem has been resolved by changing how the custom weapon is instantiated.
