### ISSUE TITLE
Can't use mod if host when have mod.

### ISSUE THREAD

**Issue by superseani2** [Hazardu/ChampionsOfForest#2]
It has already been adressed.
https://github.com/Hazardu/ChampionsOfForest/issues/1

I think the fix is simple. Make it so everyone choose there own difficulty. host could force difficulty.

**Comment by superseani2** [comment]
Can't use MOD if host doesn't have MOD, which nobody does. 99% player play Vanilla

**Comment by superseani2** [comment]
Found fix (i think ) in ChampionsOfForest.git/ModSettings.cs :: Line 10 change FALSE to TRUE ?

**Comment by Hazardu** [comment]
You can't play with vanilla players.
Firendly fire controlls if in MP players deal full dmg to each other or dont deal damage to each other at all.

Have some patience with the dedi server.
Once im done with adding content ill get rid of all the CPU heavy visuals and make it choose diff from some .txt file

**Comment by Hazardu** [comment]
I did what I promised. May be buggy, because I haven't tested it.
