### ISSUE TITLE
Nice Mod

### ISSUE THREAD

**Issue by KiidInx** [Hazardu/ChampionsOfForest#21]
Hey :)
sry for my bad english, im not so good xD

i want to say, u do a good job, but can u create Champions of the Forest for Servers?
that was really cool :D

**Comment by Hazardu** [comment]
Hi, I did attempt to make a version for dedicated servers, stripped of all visual effects, simulated physics objects and assets, but the way in which the dedi server works greatly differs from how clients, singleplayer and peer to peer hosts operate

**Comment by KiidInx** [comment]
too bad, I recently rented a The Forest server, and then discovered your mod, and since then have been looking for a way to run the mod or the ModAPI on it
