### ISSUE TITLE
21.7million exp needed to reach lvl 31

### ISSUE THREAD

**Issue by Karlfuus** [Hazardu/ChampionsOfForest#25]
i have been playing with this mod for a bit and just increased the difficulty to elite. i noticed that im getting very little exp from the huge bounties while my friend leveld up 5 times even though we were the same level when we started. i checked my stats and it said i need 21.7 MILLION exp to level up. thats absurd, how can i fix this?

**Comment by Karlfuus** [comment]
after dropping this issue, i stumbled upon another one.. after trying to return to the earlier version, i lost all my items, mutations, mutation points, my spells. The level stayed on 30 tho but i cant really do anything without my stuff and i dont know how to fix this.

**Comment by Hazardu** [comment]
Sure thing. I will do something about the level curve increasing too fast.  About the second issue, cant do anything about previous versions being incompatible with newer ones.
The new level curve will be about in between the old, pre1.5.8.1 and the 1.5.8.1 one. The polearms are a bit **completely busted** at the moment, but i guess i can still upload an update
Expect the update within 5-10 minutes to be uploaded to modapi @Karlfuus
