### ISSUE TITLE
VR needs ways to interact with challenge menu, and changes to equipment, skills, etc.

### ISSUE THREAD

**Issue by erraticengineer** [Hazardu/ChampionsOfForest#5]
Title says it.

In order to launch my game I have to take off my HMD, click to choose the threat level, disable friendly fire, and it will show the HUD on the flat version but not in the virtual game.  I don't know if it's possible to fix without an HMD, so if it's not, I just won't use the mod.  However, I would love to see this updated to support VR, as I would love a progression system in The Forest that's a bit more opaque.

**Comment by erraticengineer** [comment]
I will note that if it's like a book in the inventory and that opens up a submenu that's perfect.  It keeps the regular VR backpack and allows us to access things for the mod.  If there's a way to enable the HUD that would be nice as well.

**Comment by Hazardu** [comment]
I don't have a vr headset, I can't make mods for vr

**Comment by erraticengineer** [comment]
Fair enough, was worth asking.
