### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by StrafeMinecraft** [Hazardu/ChampionsOfForest#7]
I have ChamionsOfForest loaded on modapi and in the forest, but how do I use cheats?  The files in github are way more than what I have, I only have a .mod file.  I can't find any files to look at that are relative to cheats or adding items, etc.

**Comment by Hazardu** [comment]
COTF cheats is a class that expands on the developermodeon console. "cotfhelp" command will list all the avaible COTF commands

**Comment by StrafeMinecraft** [comment]
When I list items, it only lists about 2 items in the console log, but when I spam f1 a lot my log gets spammed with Inputstates: World True  and has the list merged with its text.  Can I change the size of my console or is there some other cause to why I can't see the whole list?

**Comment by Hazardu** [comment]
Hey,
As far as I know, you can't scale the console. Only way to see more is by hovering over the message log. Then it's displayed in a large box. If the message is longer than the large box, then it can't be fully displayed. I made it some COTFs commands also write the message to a log file. 

About the input state - the log is made in endnights vanilla code, indicates the cursor changed to visible/hidden, or that it was locked/unlocked. It also indicates that player itself got locked or unlocked, toggling movement like falling, wasd input, rotating camera.

**Comment by StrafeMinecraft** [comment]
Thanks, I hovered and screenshotted it.  I'll just use it as reference.
