### ISSUE TITLE
Add all items

### ISSUE THREAD

**Issue by DJcrafter13** [Hazardu/ChampionsOfForest#8]
Ability to add all or specific items into your backpack, like swords and stuff. Maybe also add lvls, please update this mod more!

**Comment by Hazardu** [comment]
So, cheat codes?
Already added.

enable developermodeon in main menu and then write cotfhelp command. it will list all possible commands for the mod. 
You can add items with cotfspawnitem x y where x is the item ID and y is the desired level of the item
To get IDs you need to use cotflistallitems. the result is really long and it doesn't fully display at the console that you open with f2, so you can open a log file of champions of the forest to view it all. 

Sorry for not updating the mod, but simply after so long without any updates of the game I got a little bored of it, and I stopped playing the game at all

**Comment by Hazardu** [comment]
Also I have a unpublished version where I've only fixed a bug noone but me noticed.
it had to do something with backstabbing 
back Stab would trigger when enemy lost the intention to attack a player, for example when it was shaking the fire off him. If the player were to get behind a enemy
