### ISSUE TITLE
Partner data in hosted game not saved

### ISSUE THREAD

**Issue by SeeGEye** [Hazardu/ChampionsOfForest#9]
We were playing for some time. She reached Level 8, acquired gear, picked skills, and none of it saved when quitting the game. My data saved however.

**Comment by Hazardu** [comment]
Hey, was she a host, or the client? Did her vanilla stats and inventory save?

**Comment by SeeGEye** [comment]
I was the host. Vanilla inventory and stats saved.

**Comment by SeeGEye** [comment]
Going to try validating everything again on her side to see if that helps. Also reinstalling all mods.

**Comment by Hazardu** [comment]
well, according to the saving script, https://github.com/Hazardu/ChampionsOfForest/blob/master/Serializer.cs
There is an option that a game progress isn't saved, but that doesn't influence clients. Can you check if a save file was created for her?
The path is The forest instalation folder/mods/champions of the forest/multiplayer and there should be a really long name folder, that's the lobby I'd. if there's more than one sort by date which one is most recent and matches when you played last.
